version: "3"

services:
  api:
    build:
      context: ./apigw
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - authservice
      - redis
      - salchipapitas

  authservice:
    build:
      context: ./authservice
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  salchipapitas:
    build:
      context: ./salchipapitas
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - authservice
      - redis
  besoscerezas:
    build:
      context: ./besoscerezas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
  cachetadacontrucha:
    build:
      context: ./cachetadacontrucha
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
